# Generated by Django 3.1.1 on 2020-10-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='item_url',
            field=models.CharField(default='https://books.rakuten.co.jp/', max_length=255),
        ),
    ]
