# Generated by Django 3.1.1 on 2020-09-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('change_content', 'Change content'), ('delete_content', 'Delete content'))},
        ),
    ]
