# Generated by Django 3.1.1 on 2020-10-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto'),
        ('posts', '0002_book_item_url'),
    ]

    operations = [
    ]
