# Generated by Django 3.1.1 on 2020-09-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_ahare_bookmark_comment_nice_wokashi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavComment',
        ),
    ]
