# Generated by Django 3.1.1 on 2020-09-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200907_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('change_comment_column', 'Change comment column'), ('delete_comment_column', 'Delete comment column'))},
        ),
    ]
