# Generated by Django 3.1.1 on 2020-09-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200907_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('change_delete_comment', 'Change Delete comment'),)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('change_delete_content', 'Change Delete content'),)},
        ),
    ]
