# Generated by Django 3.1.1 on 2020-10-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201022_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='comment',
        ),
    ]
