# Generated by Django 3.1.1 on 2020-10-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201022_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
