# Generated by Django 3.1.1 on 2020-10-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post_id',
        ),
        migrations.AddField(
            model_name='review',
            name='book_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.book'),
        ),
    ]
